### ISSUE TITLE
Further Information Request About The RAW Data

### ISSUE THREAD

**Issue by JiangtianPan** [yjsunnn/FBANet#10]
Hi,
I am excited about this work's result, and I appreciate your open source. May I wonder how to use the "Raw Data" in the dataset? 

Firstly, the data are all PNG files, rather than binary files. Secondly, the information obtained from the ".pkl" file is also confusing, without a script, users may not be able to use them to train or test the model. 

Could you please exhibit a script to preprocess the raw dataset that can be used to feed the model?

Many thanks for your time.

**Comment by yjsunnn** [comment]
Sure. The original file of raw processing is on the remote server which has collapsed for a long time, that's why we haven't uploaded an official version of raw data. But I have some temporary files on my own laptop, and I think it will help! The files could be found in the [[baidu link]](https://pan.baidu.com/s/1TBtsYn5LaidRO11lYGdk9Q?pwd=tb4k). It contains the data processing part, training part, evaluation part (in the test part of train.py), etc.

**Comment by yjsunnn** [comment]
And I think the following answer from [[another issue]](https://github.com/yjsunnn/FBANet/issues/7#issuecomment-1850344104) gonna help.

> For the raw model, actually there are two ways you can choose: 1) Import the 4-channel data (80x80x4), flatten it (160x160x1) and use the default demosaic function in colour_demosaicing to demosaic it (160x160x3). The rest is quite the same as in RGB. (Our choice); Or 2) Import the 4-channel data, change the first convolution (as you have said, from 3 to 4) and add one more upsampler layer (A popular choice). You can try both ways, and welcome to discuss the results!

**Comment by yjsunnn** [comment]
Please feel free to re-open the issue if you have any problem.
