### ISSUE TITLE
About the raw image

### ISSUE THREAD

**Issue by X1-Wang** [yjsunnn/FBANet#11]
Could you please share the process for aligning raw images and explain how the "_rgb.png" images are generated within each image set? I don't understand why the _rgb.png images are so dark

**Comment by yjsunnn** [comment]
[raw_align.txt](https://github.com/yjsunnn/FBANet/files/14848613/raw_align.txt)
The original files are missing due to the long-time remote server collapse (that's why some codes haven't been uploaded yet), so I re-write some necessary processing codes according to my memory. Please let me know if the code has any problem.

As for the '.png' image in the dataset, we adopt the exactly same processing pipelines as DBSR, for a fully-fair comparison. The "dark" image is the linear image, which is different from the sRGB image that we are used to. You can refer to the below files for the visualization.
[post_processing_vis.txt](https://github.com/yjsunnn/FBANet/files/14848736/post_processing_vis.txt)
[raw_train.txt](https://github.com/yjsunnn/FBANet/files/14848738/raw_train.txt)

**Comment by yjsunnn** [comment]
Please feel free to re-open the issue if you have any question~

**Comment by AndersonCotrim** [comment]
Hi, first, congratulations for this awesome work. I have a couple of questions related to this issue. 

Firstly, is it not necessary to align the gt with the base frame (raw_align.txt)?  I notice some misalignment between them in RAW dataset, which is not present in RGB dataset. 

Secondly, I would like to ask if it is possible to share the checkpoint for the RAW data.

Thanks in advance
