### ISSUE TITLE
About RAW data

### ISSUE THREAD

**Issue by AndersonCotrim** [yjsunnn/FBANet#12]
Hi, first, congratulations for this awesome work. I have a couple of questions related to this issue. 

Firstly, is it not necessary to align the gt with the base frame (raw_align.txt)?  I notice some misalignment between them in RAW dataset, which is not present in RGB dataset. 

Secondly, I would like to ask if it is possible to share the checkpoint for the RAW data.

Thanks in advance

**Comment by yjsunnn** [comment]
Hi, for the first question, you're right, there is no need for the extra alignment between gt and base frame for raw data since the misalignment among them is so subtle that CoBi loss during training could handle it. However, the misalignment among base frame and gt for raw data is still a significant problem that needs to be solved, and the performance would be much better if the misalignment could be resolved. For the second question, I'm very sorry that many files have been missing due to the collapse of remote server as I have mentioned in some issues. Please feel free to contact me via email or github if you have any problem during re-production.

**Comment by yjsunnn** [comment]
I close this issue, please feel free to re-open it or directly contact me via email.
