### ISSUE TITLE
An error in Tab. 5 in your paper

### ISSUE THREAD

**Issue by yangzheng-yz** [yjsunnn/FBANet#2]
In Table 5, it seems that burst==10 's SSIM and LPIPS is better than burst == 14. 

Does it mean no need too many burst, or there may be a optimal number for burst SR.

**Comment by yjsunnn** [comment]
Actually, we also conduct the experiments of 18 frames under the exactly same experimental setting, and the result is not better than that of 14 frames in terms of PSNR, SSIM and LPIPS. We don't think that the performance will definitely increase with more input frames. But we have not been able to confirm the optimal frame number. So, back to your question, 1) you can consider fewer frames, it's ok 2) Due to the limitation of computational resources, we are not sure about the optimal frame number. Hope it helps XD
