### ISSUE TITLE
UnboundLocalError: local variable 'tensor' referenced before assignment

### ISSUE THREAD

**Issue by yangzheng-yz** [yjsunnn/FBANet#7]
I downloaded your dataset through BaiduNetDisk link. The test image in your folder is 160*160. And your 'psize' in test_in_any_resolution.py is set to 80 so that the error occurs. How should I change the psize and overlap to run the program properly. A simple change will also result in other errors related to your network shape.... It is really wierd.

**Comment by yangzheng-yz** [comment]
it seems that your model can only accept 160*160 input directly?

**Comment by yangzheng-yz** [comment]
And only accept burst==14???

**Comment by yjsunnn** [comment]
For the first issue (about the psize=80), the calculation is psize+2*overlap=160, so if psize=80, then overlap is 40. Secondly, for the input 160x160, if you're training the network from scratch, then the network input is supposed to be divided by 4 (as there are 2 downsample operations). If you're using the checkpoint, then the patch_size is fixed, you could use the test_in_any_resolution.py to solve it (But it is aimed to resolution > 160x160). Thirdly, for the burst_size, if you're training from scratch, there is no restriction of frame number. You can change the burst_size assertion in ManualDataset.py which is just the alertion for our paper. And if you're using the checkpoint, it is fixed to accept the burst_size of 14. 

Actually, for the issue reported in the title, I think it may be caused by the psize setting. Maybe you can change it to like 52/81/93... and adjusts the overlap as the appropriate number to meet the 160 requirement.

**Comment by yangzheng-yz** [comment]
Thanks for your patient reply! It is exactly what I think... 

But in your paper, you also showed the metrics on the SyntheticBurst Dataset. I noticed that the DBSR and MFIR's metrics are reported in their paper, in which they use burst==14, 96*96-->384*384 super resolution. Therefore, I would like to know if you trained another model on the SyntheticBurst Dataset from scratch? Could you please also provide the weight which can repeat your result on SyntheticBurst Dataset?


Also, I would like to ask if it is a problem of the network architecture which limits this network to only accept fixed burst input and fixed size once it is trained?

**Comment by yjsunnn** [comment]
For the Synthetic Burst, do you mean synthetic RealBSR or the zurich dataset used in DBSR? And for the network limitation, actually it inherits the limitation of CeiT and Uformer (two basic networks we build our network on).

**Comment by yangzheng-yz** [comment]
the zurich dataset used in DBSR

**Comment by yjsunnn** [comment]
Sure. I will release the checkpoint soon (Maybe in this week).

**Comment by yjsunnn** [comment]
Hi, sorry about the previous careless answer. Actually, for both zurich-dataset and burstsr-dataset, there are very serious issues which would mislead the model to a large content. 

- For zurich and burstsr dataset, the data processing pipeline could be visualized as below. As the figure shows, the demosaic step indicates that there are quite many "generated" details hidden in HR, misleading the model to a large content.
![image](https://github.com/yjsunnn/FBANet/assets/54736521/5fbe4063-9a67-442c-9246-525a13c3179f)

- For burstsr dataset, the issues are listed in the paper. And extensive experiments show that the numeric result on the burstsr dataset have no positive relationship with the real capability of the model itself.

Based on above reasons, we may not provide direct link (If you have any issues during reproduction, please feel free to contact us). And plus, if you're interested in using synthetic dataset for pretraining, it would be much better to consider the DF (Div2K+Flickr2K) dataset, based on our experiments, as the HR to generate corresponding LRs following the guidance provided by DBSR. Here are the links of Div2K and Flickr: [Div2K](https://cv.snu.ac.kr/research/EDSR/DIV2K.tar) and [Flickr2k](https://cv.snu.ac.kr/research/EDSR/Flickr2K.tar).

**Comment by yangzheng-yz** [comment]
Thank you so much for your detailed response. It really helps me a lot to understand burst superresolution. I would like to further enquire two questions:
1. what do you mean "a large content"? Does it mean the model will be large? or the model tends to generate large but unuseful content?
2. I noticed that the MFIR method tested on your Real-RGB dataset with PSNR-30.895, SSIM-0.098, which is comparable to FBAnet with PSNR-31.012(+0.117dB), SSIM-0.102(+0.004), but when the situation turns to Real-RAW dataset, MFIR is much inferiorer than your FBAnet, what do you think of this difference? And may I know the difference when you process the RGB and RAW input for MFIR, cause MFIR is designed for RAW input only in their paper?(DO you just replace the input channel==4 at the first conv with input channel==3?)

Look forward to your reply!

**Comment by yjsunnn** [comment]
1. For the "to a large content", I mean "extremely" since the demosaic operation adds a lot of "generated information" to the original data, which relates the reconstruction quality of model closely to the reliability of introduced demosaic function. 
2. For the result comparison, there is a domain gap among raw data and rgb data. Consequently, it's quite normal for the different performances. To be specific, we think our model and adopted loss functions are more reasonable to explore the abundant information in raw-data.
3. For the raw model, actually there are two ways you can choose: 1) Import the 4-channel data (80x80x4), flatten it (160x160x1) and use the default demosaic function in colour_demosaicing to demosaic it (160x160x3). The rest is quite the same as in RGB. (Our choice); Or 2) Import the 4-channel data, change the first convolution (as you have said, from 3 to 4) and add one more upsampler layer (A popular choice). You can try both ways, and welcome to discuss the results!

**Comment by yjsunnn** [comment]
I close issue and please feel free to re-open it or make a new issue.
